NAME_POS_VARIABLE = "pos"
NAME_AUTO_ANIM    = "gfx"

POS_TEXT_SAVE_Y         = 76

POS_PHOTO_PIECE_TEXT    = (0x80, 100)
POS_HAMSTER_TEXT        = (0x80, 0x5c)

POS_STOCK_SCREEN_NAZO_ICON  = (0x74, 0x3c)
POS_LOST_SCREEN_PIECE_ICON  = (0, 0x38)
POS_PHOTO_PIECE_PIECE_ICON  = (0x74, 0x3a)

ID_STOCK_SCREEN         = 0xcc
ID_SAVE_NOT_COMPLETE    = 0xd0
ID_SAVE_COMPLETE        = 0xd1
ID_PHOTO_NEW_FOUND      = 0xd4
ID_NAMING_HAM           = 0xd7
ID_LOST_SCREEN          = 0xd8
ID_PHOTO_ALL_FOUND      = 0xde
ID_PHOTO_NEARLY_FOUND   = 0x640

PATH_ANIM_BUTTON_YES = "system/btn/%s/yes.spr"
PATH_ANIM_BUTTON_NO = "system/btn/%s/no.spr"