NAME_POS_VARIABLE = "pos"

POS_TEXT_SAVE_Y = 76

POS_STOCK_SCREEN_NAZO_ICON = (0x74, 0x3c)

ID_SAVE_NOT_COMPLETE = 0xd0
ID_SAVE_COMPLETE     = 0xd1
ID_STOCK_SCREEN      = 0xcc

PATH_ANIM_BUTTON_YES = "system/btn/%s/yes.spr"
PATH_ANIM_BUTTON_NO = "system/btn/%s/no.spr"